apiVersion: v1
kind: Service              
metadata:
  name: coit-frontend-lb
spec: 
  type: LoadBalancer
  ports:
  - port: 80               
    protocol: TCP          
    targetPort: 80         
  selector:                
    app: coit-frontend       
